version: '3.5'

services:
  plotlabserver:
    image: plotlabserver:latest
    container_name: plotlabserver
    hostname: plotlabserver
    build:
      context: .
      dockerfile: Dockerfile.plotlabserver
    network_mode: "host"
    ipc: "host"
    #entrypoint: sh -c '(xeyes &) && ./plotlabserver'
    #entrypoint: sh -c 'tail -f /dev/null'
    environment:
      #- DISPLAY_MODE=${DISPLAY_MODE:-native}
      - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      #- DISPLAY_MODE=${DISPLAY_MODE:-headless}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    ports:
      - 12345:12345
      - 12346:12346
      - 12347:12347
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .log:/var/log/plotlab
