services:
  plotlabserver:
    extends:
      file: ${PLOTLABSERVER_MAKEFILE_PATH}/plotlabserver.yaml
      service: plotlabserver
    environment:
      - DISPLAY_MODE=${DISPLAY_MODE:-native}
      # - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      # - DISPLAY_MODE=${DISPLAY_MODE:-headless}
