version: '3.5'

services:
  plotlabserver:
    privileged: true
    image: plotlabserver:${PLOTLABSERVER_TAG:-latest}
    container_name: plotlabserver
    hostname: plotlabserver
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: Dockerfile.plotlabserver
      network: "host"
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1001}
        - PLOTLABSERVER_TAG=${PLOTLABSERVER_TAG:-latest}
    network_mode: "host"
    ipc: "host"
    #entrypoint: sh -c 'xeyes'
    #entrypoint: sh -c '(xeyes &) && ./plotlabserver'
    #entrypoint: sh -c 'tail -f /dev/null'
    #entrypoint: sh -c 'glxgears'    
    environment:
      - DISPLAY_MODE=${DISPLAY_MODE:-native}
      # - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      #- DISPLAY_MODE=${DISPLAY_MODE:-headless}
      - DISPLAY=${DISPLAY}
      #- LIBGL_ALWAYS_SOFTWARE=1
      - UID=${UID}
      - GID=${GID}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .log:/var/log/plotlab
      
