services: 
  plotlabserver:
    privileged: true
    image: plotlabserver:${PLOTLABSERVER_TAG}
    container_name: plotlabserver
    hostname: plotlabserver
    user: ${UID}:${GID}
    build:
      context: ${PLOTLABSERVER_MAKEFILE_PATH}
      dockerfile: Dockerfile.plotlabserver
      network: host
      args:
        - UID=${UID}
        - GID=${GID}
        - PLOTLABSERVER_TAG=${PLOTLABSERVER_TAG}
    network_mode: "host"
    ipc: "host"
    #entrypoint: sh -c 'xeyes'
    #entrypoint: sh -c '(xeyes &) && ./plotlabserver'
    #entrypoint: sh -c 'tail -f /dev/null'
    #entrypoint: sh -c 'glxgears'    
    environment:
      #- DISPLAY_MODE=${DISPLAY_MODE:-native}
      # - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      #- DISPLAY_MODE=${DISPLAY_MODE:-headless}
      - DISPLAY=${DISPLAY}
      #- LIBGL_ALWAYS_SOFTWARE=1
      - UID=${UID}
      - GID=${GID}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PLOTLABSERVER_MAKEFILE_PATH}/.log:/var/log/plotlabserver
      
