name: CI
on: push

jobs:
  install_requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Install GNU Make
      run: sudo apt-get update && sudo apt-get -y install make

  clone_source:
    runs-on: ubuntu-latest
    needs: install_requirements 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Save workspace
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: ./
          
  build:
    runs-on: ubuntu-latest
    needs: clone_source
    steps:
      - name: Load workspace 
        uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: Load docker cache 
        uses: actions/checkout@v3
        uses: docker/setup-buildx-action@v1
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build 
        run: make ci_build
      - name: Save docker images 
        run: make save_docker_images || true
      - name: Save workspace
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: ./

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Load workspace 
        uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: Load docker images 
        run: make load_docker_images || true
      - name: Test
        run: make ci_test
